<?php

namespace BlogBundle\Repository;

/**
 * AlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPosts()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.message', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}

