<?php

namespace BlogBundle\Repository;

/**
 * CadreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadreRepository extends \Doctrine\ORM\EntityRepository
{
}
