<?php

namespace BlogBundle\Repository;

/**
 * TLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TLRepository extends \Doctrine\ORM\EntityRepository
{
}
